/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.healthapp.homepage;

public final class R {
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int image=0x7f010000;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int text=0x7f010001;
    }
    public static final class color {
        public static final int black=0x7f060001;
        public static final int blue=0x7f060005;
        public static final int green=0x7f060000;
        public static final int main_button_color_selector=0x7f060007;
        public static final int orange=0x7f060004;
        public static final int red=0x7f060003;
        public static final int transparent=0x7f060006;
        public static final int white=0x7f060002;
    }
    public static final class drawable {
        public static final int beat=0x7f020000;
        public static final int ecg=0x7f020001;
        public static final int main_button_border=0x7f020002;
        public static final int spo2=0x7f020003;
        public static final int thermometer=0x7f020004;
    }
    public static final class id {
        public static final int ecg=0x7f090007;
        public static final int exit_button=0x7f090003;
        public static final int heartbeat=0x7f090005;
        public static final int home_main_text=0x7f090001;
        public static final int spo2=0x7f090006;
        public static final int start_button=0x7f090002;
        public static final int temperature=0x7f090004;
        public static final int video_view=0x7f090000;
    }
    public static final class layout {
        public static final int homepage_activity=0x7f040000;
        public static final int main_activity=0x7f040001;
    }
    public static final class mipmap {
        public static final int logo=0x7f030000;
        public static final int logo1=0x7f030001;
    }
    public static final class raw {
        public static final int healthapp_background=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f070000;
        public static final int hello_msg=0x7f070001;
        public static final int menu_settings=0x7f070002;
        public static final int title_activity_main=0x7f070003;
    }
    public static final class style {
        public static final int MainButtonStyle=0x7f080000;
    }
    public static final class styleable {
        /** Attributes that can be used with a Element.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #Element_image com.healthapp.homepage:image}</code></td><td></td></tr>
           <tr><td><code>{@link #Element_text com.healthapp.homepage:text}</code></td><td></td></tr>
           </table>
           @see #Element_image
           @see #Element_text
         */
        public static final int[] Element = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link com.healthapp.homepage.R.attr#image}
          attribute's value can be found in the {@link #Element} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.healthapp.homepage:image
        */
        public static final int Element_image = 0;
        /**
          <p>This symbol is the offset where the {@link com.healthapp.homepage.R.attr#text}
          attribute's value can be found in the {@link #Element} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.healthapp.homepage:text
        */
        public static final int Element_text = 1;
    };
}
